info:
  component: Config Server
spring:
  application:
    name: configserver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  profiles:
    active: git,native,vault
  cloud:
    config:
      server:
#        health:
#          enabled: false
        bootstrap: true
        vault:
          host: localhost
          port: 8200
          backend: ir
          order: 2
        git:
          uri: file://${HOME}/git
          order: 1
        native:
          searchLocations: file://${HOME}/native
          order: 0

server:
  port: 8888
management:
  context_path: /admin
